import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

export const generateLongevityAudit = async (userData, predictions, dashboardElementId) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // Header Background
  doc.setFillColor(15, 23, 42); // Navy
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Logo Placeholder
  doc.setTextColor(0, 245, 212); // Teal
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('LIFELYTICS', margin, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text('AI-DRIVEN LONGEVITY AUDIT', margin, 32);

  // User Info Section
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.text('Patient Health Profile', margin, 55);
  
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, 58, pageWidth - margin, 58);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  
  const infoY = 68;
  doc.text(`Age: ${userData.age}`, margin, infoY);
  doc.text(`BMI: ${userData.bmi}`, margin + 40, infoY);
  doc.text(`Gender: ${userData.gender}`, margin + 80, infoY);
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, margin + 120, infoY);

  // Prediction Results
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, 80, pageWidth - (margin * 2), 50, 3, 3, 'F');
  
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.text('Predicted Lifespan', margin + 10, 95);
  
  doc.setFontSize(48);
  doc.setTextColor(0, 245, 212);
  doc.text(`${predictions.prediction}`, margin + 10, 115);
  
  doc.setFontSize(14);
  doc.setTextColor(100, 116, 139);
  doc.text('Years', margin + 35, 115);

  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(`Base: ${predictions.base} years`, margin + 100, 100);
  doc.text(`Neural Modifier: ${predictions.totalModifier > 0 ? '+' : ''}${predictions.totalModifier}`, margin + 100, 110);
  doc.text(`Engine: Hybrid Neural-Actuarial`, margin + 100, 120);

  // Charts Section (Captured from DOM)
  const dashboardElement = document.getElementById(dashboardElementId);
  if (dashboardElement) {
    try {
      // We'll capture specific chart containers instead of the whole dashboard
      const charts = dashboardElement.querySelectorAll('.glass-panel');
      if (charts.length >= 2) {
        const canvas1 = await html2canvas(charts[0], { scale: 2 });
        const imgData1 = canvas1.toDataURL('image/png');
        doc.addImage(imgData1, 'PNG', margin, 140, 80, 60);

        const canvas2 = await html2canvas(charts[1], { scale: 2 });
        const imgData2 = canvas2.toDataURL('image/png');
        doc.addImage(imgData2, 'PNG', margin + 90, 140, 80, 60);
      }
    } catch (e) {
      console.error("Chart capture failed", e);
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  const footerText = "CONFIDENTIAL: This report is generated by Lifelytics AI and is for informational purposes only. Consult a physician before making major lifestyle changes.";
  const splitFooter = doc.splitTextToSize(footerText, pageWidth - (margin * 2));
  doc.text(splitFooter, margin, pageHeight - 15);

  doc.save(`Lifelytics_Audit_${new Date().toISOString().split('T')[0]}.pdf`);
};
